<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Components\Shared\RadiusifierMainCard.razor.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\Shared\RadiusifierMainCard.razor.cs" />
  </ItemGroup>

</Project>
